create_news_job:
  cron: "* * * * *"
  class: "CreateNewsJob"   
  queue: default 

# create_update_vehicle_job:
#   cron: "* * * * *"
#   class: "CreateUpdateVehicleJob"  
#   queue: default 

# get_vehicle_location_job:
#   cron: "* * * * *"
#   class: "GetVehicleLocationsJob"  
#   queue: default 

  